version: '3.9'
services:
  rabbitmq:
    build:
      context: ./rabbitmq
    ports:
      - 15672:15672
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 10s
      timeout: 5s
      retries: 10

  post_handler:
    container_name: post_handler
    build:
      context: ./post_handler
      dockerfile: Dockerfile
    image: post_handler:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FLIGHTS_FILTER_PLUS_AMOUNT=1
      - AIRPORTS_HANDLER_AMOUNT=1
      - FLIGHTS_FILTER_AVG_AMOUNT=2
    volumes:
      - ./post_handler/config.ini:/config.ini
      - ./utils:/utils
      - ./middleware:/middleware
    ports:
      - 12345:12345
  
  file_writer:
    container_name: file_writer
    build:
      context: ./file_writer
      dockerfile: Dockerfile
    image: file_writer:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./file_writer/config.ini:/config.ini
      - ./file_writer/:/out_files/
      - ./utils:/utils
  flights_filter_avg_1:
    container_name: flights_avg_1
    build:
      context: ./flights_avg
      dockerfile: Dockerfile
    image: flights_avg:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FLIGHTS_FILTER_AVG_AMOUNT=2
      - ID=1
      - JOIN_AVG_AMOUNT=2
    volumes:
      - ./flights_avg/config.ini:/config.ini
      - ./utils:/utils
      - ./middleware:/middleware
  flights_filter_avg_2:
    container_name: flights_avg_2
    build:
      context: ./flights_avg
      dockerfile: Dockerfile
    image: flights_avg:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FLIGHTS_FILTER_AVG_AMOUNT=2
      - ID=2
      - JOIN_AVG_AMOUNT=2
    volumes:
      - ./flights_avg/config.ini:/config.ini
      - ./utils:/utils
      - ./middleware:/middleware
  flights_join_avg_1:
    container_name: flights_join_avg_1
    build:
      context: ./join_avg
      dockerfile: Dockerfile
    image: join_avg:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - ID=1
    volumes:
      - ./join_avg/config.ini:/config.ini
      - ./utils:/utils
      - ./middleware:/middleware
  flights_join_avg_2:
    container_name: flights_join_avg_2
    build:
      context: ./join_avg
      dockerfile: Dockerfile
    image: join_avg:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - ID=2
    volumes:
      - ./join_avg/config.ini:/config.ini
      - ./utils:/utils
      - ./middleware:/middleware
  

