version: '3.9'
services:
  rabbitmq:
    build:
      context: ./rabbitmq
    ports:
      - 15672:15672
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 10s
      timeout: 5s
      retries: 10

  post_handler_1:
    container_name: post_handler_1
    build:
      context: ./post_handler
      dockerfile: Dockerfile
    image: post_handler:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FLIGHTS_FILTER_PLUS_AMOUNT=2
      - AIRPORTS_HANDLER_AMOUNT=2
      - FLIGHTS_FILTER_AVG_AMOUNT=2
      - POST_HANDLER_ID=1
    volumes:
      - ./post_handler/config.ini:/config.ini
      - ./utils:/utils
      - ./middleware:/middleware
    ports:
      - 12351:12351
  post_handler_2:
    container_name: post_handler_2
    build:
      context: ./post_handler
      dockerfile: Dockerfile
    image: post_handler:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FLIGHTS_FILTER_PLUS_AMOUNT=2
      - AIRPORTS_HANDLER_AMOUNT=2
      - FLIGHTS_FILTER_AVG_AMOUNT=2
      - POST_HANDLER_ID=2
    volumes:
      - ./post_handler/config.ini:/config.ini
      - ./utils:/utils
      - ./middleware:/middleware
    ports:
      - 12352:12352
  flights_filter_plus_3_1:
    container_name: flights_filter_1
    build:
      context: ./flights_filter
      dockerfile: Dockerfile
    image: flights_filter:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FLIGHTS_FILTER_PLUS_AMOUNT=2
      - FLIGHTS_MAX_AMOUNT=2
      - FLIGHT_FILTER_ID=1
    volumes:
      - ./flights_filter/config.ini:/config.ini
      - ./utils:/utils
      - ./middleware:/middleware
  flights_filter_plus_3_2:
    container_name: flights_filter_2
    build:
      context: ./flights_filter
      dockerfile: Dockerfile
    image: flights_filter:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FLIGHTS_FILTER_PLUS_AMOUNT=2
      - FLIGHTS_MAX_AMOUNT=2
      - FLIGHT_FILTER_ID=2
    volumes:
      - ./flights_filter/config.ini:/config.ini
      - ./utils:/utils
      - ./middleware:/middleware
  flights_filter_max_1:
    container_name: flights_max_1
    build:
      context: ./flights_max
      dockerfile: Dockerfile
    image: flights_max:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FLIGHTS_MAX_ID=1
      - FLIGHTS_MAX_AMOUNT=2
    volumes:
      - ./flights_max/config.ini:/config.ini
      - ./utils:/utils
      - ./middleware:/middleware
  flights_filter_max_2:
    container_name: flights_max_2
    build:
      context: ./flights_max
      dockerfile: Dockerfile
    image: flights_max:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FLIGHTS_MAX_ID=2
      - FLIGHTS_MAX_AMOUNT=2
    volumes:
      - ./flights_max/config.ini:/config.ini
      - ./utils:/utils
      - ./middleware:/middleware
  file_writer:
    container_name: file_writer
    build:
      context: ./file_writer
      dockerfile: Dockerfile
    image: file_writer:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./file_writer/config.ini:/config.ini
      - ./file_writer/:/out_files/
      - ./utils:/utils
