version: '3.9'
services:
  manager_1:
    container_name: manager_1
    build:
      context: ./manager
      dockerfile: Dockerfile
    image: manager:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
      - MANAGER_ID=1
      - MANAGER_AMOUNT=3
      - LAYER={'flights_filter_':2,'flights_max_':2,'flights_avg_':2,'flights_mayor_avg_':2,'flights_avg_by_journey_':2,'flights_filter_distance_':2}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  manager_2:
    container_name: manager_2
    build:
      context: ./manager
      dockerfile: Dockerfile
    image: manager:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
      - MANAGER_ID=2
      - MANAGER_AMOUNT=3
      - LAYER={'flights_filter_':2,'flights_max_':2,'flights_avg_':2,'flights_mayor_avg_':2,'flights_avg_by_journey_':2,'flights_filter_distance_':2}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  manager_3:
    container_name: manager_3
    build:
      context: ./manager
      dockerfile: Dockerfile
    image: manager:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
      - MANAGER_ID=3
      - MANAGER_AMOUNT=3
      - LAYER={'flights_filter_':2,'flights_max_':2,'flights_avg_':2,'flights_mayor_avg_':2,'flights_avg_by_journey_':2,'flights_filter_distance_':2}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
