version: '3.9'
services:
  rabbitmq:
    build:
      context: ./rabbitmq
    ports:
      - 15672:15672
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 10s
      timeout: 5s
      retries: 10

  post_handler:
    container_name: post_handler
    build:
      context: ./post_handler
      dockerfile: Dockerfile
    image: post_handler:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FLIGHTS_FILTER_PLUS_AMOUNT=2
    volumes:
      - ./post_handler/config.ini:/config.ini
      - ./utils:/utils
      - ./middleware:/middleware
    ports:
      - 12345:12345
  flights_filter_plus_3_1:
    container_name: flights_filter_1
    build:
      context: ./flights_filter
      dockerfile: Dockerfile
    image: flights_filter:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FLIGHTS_FILTER_PLUS_AMOUNT=2 
      - FLIGHTS_MAX_AMOUNT=2
      - FLIGHT_FILTER_ID=1
    volumes:
      - ./flights_filter/config.ini:/config.ini
      - ./utils:/utils
      - ./middleware:/middleware
  flights_filter_plus_3_2:
    container_name: flights_filter_2
    build:
      context: ./flights_filter
      dockerfile: Dockerfile
    image: flights_filter:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FLIGHTS_FILTER_PLUS_AMOUNT=2 
      - FLIGHTS_MAX_AMOUNT=2
      - FLIGHT_FILTER_ID=2
    volumes:
      - ./flights_filter/config.ini:/config.ini
      - ./utils:/utils
      - ./middleware:/middleware
  flights_filter_max_1:
    container_name: flights_max_1
    build:
      context: ./flights_max
      dockerfile: Dockerfile
    image: flights_max:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FLIGHTS_MAX_ID=1
      - FLIGHTS_MAX_AMOUNT=2
    volumes:
      - ./flights_max/config.ini:/config.ini
      - ./utils:/utils
      - ./middleware:/middleware
  flights_filter_max_2:
    container_name: flights_max_2
    build:
      context: ./flights_max
      dockerfile: Dockerfile
    image: flights_max:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FLIGHTS_MAX_ID=2
      - FLIGHTS_MAX_AMOUNT=2
    volumes:
      - ./flights_max/config.ini:/config.ini
      - ./utils:/utils
      - ./middleware:/middleware
  file_writer:
    container_name: file_writer
    build:
      context: ./file_writer
      dockerfile: Dockerfile
    image: file_writer:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./file_writer/config.ini:/config.ini
      - ./file_writer/:/out_files/
      - ./utils:/utils
  flights_filter_avg_1:
    container_name: flights_avg_1
    build:
      context: ./flights_avg
      dockerfile: Dockerfile
    image: flights_avg:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FLIGHTS_FILTER_AVG_AMOUNT=2
      - FLIGHTS_MAYOR_AVG_AMOUNT=2
    volumes:
      - ./flights_avg/config.ini:/config.ini
      - ./utils:/utils
      - ./middleware:/middleware
  flights_filter_avg_2:
    container_name: flights_avg_2
    build:
      context: ./flights_avg
      dockerfile: Dockerfile
    image: flights_avg:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FLIGHTS_FILTER_AVG_AMOUNT=2
      - FLIGHTS_MAYOR_AVG_AMOUNT=2
    volumes:
      - ./flights_avg/config.ini:/config.ini
      - ./utils:/utils
      - ./middleware:/middleware
  flights_join_avg:
    container_name: flights_join_avg
    build:
      context: ./join_avg
      dockerfile: Dockerfile
    image: join_avg:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./join_avg/config.ini:/config.ini
      - ./utils:/utils
      - ./middleware:/middleware
  flights_mayor_avg_1:
    container_name: flights_mayor_avg_1
    build:
      context: ./flights_mayor_avg
      dockerfile: Dockerfile
    image: flights_mayor_avg:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FLIGHTS_MAYOR_AVG_ID=1
      - FLIGHTS_MAYOR_AVG_AMOUNT=2
      - FLIGHTS_AVG_JOURNEY_AMOUNT=2
    volumes:
      - ./flights_mayor_avg/config.ini:/config.ini
      - ./utils:/utils
      - ./middleware:/middleware
  flights_mayor_avg_2:
    container_name: flights_mayor_avg_2
    build:
      context: ./flights_mayor_avg
      dockerfile: Dockerfile
    image: flights_mayor_avg:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FLIGHTS_MAYOR_AVG_ID=2
      - FLIGHTS_MAYOR_AVG_AMOUNT=2
      - FLIGHTS_AVG_JOURNEY_AMOUNT=2
    volumes:
      - ./flights_mayor_avg/config.ini:/config.ini
      - ./utils:/utils
      - ./middleware:/middleware
  airport_fligths_handler:
    container_name: airport_fligths_handler
    build:
      context: ./airport_fligths_handler
      dockerfile: Dockerfile
    image: airport_fligths_handler:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./utils:/utils
      - ./middleware:/middleware

  flights_filter_distance_1:
    container_name: flights_filter_distance_1
    build:
      context: ./flights_filter_distance
      dockerfile: Dockerfile
    image: flights_filter_distance:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FLIGHTS_FILTER_DISTANCE_AMOUNT=2
    volumes:
      - ./flights_filter_distance/config.ini:/config.ini
      - ./utils:/utils
      - ./middleware:/middleware
  flights_filter_distance_2:
    container_name: flights_filter_distance_2
    build:
      context: ./flights_filter_distance
      dockerfile: Dockerfile
    image: flights_filter_distance:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FLIGHTS_FILTER_DISTANCE_AMOUNT=2
    volumes:
      - ./flights_filter_distance/config.ini:/config.ini
      - ./utils:/utils
      - ./middleware:/middleware
  flights_avg_by_journey_1:
    container_name: flights_avg_by_journey_1
    build:
      context: ./flights_avg_by_journey
      dockerfile: Dockerfile
    image: flights_avg_by_journey:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FLIGHTS_AVG_JOURNEY_ID=1
      - FLIGHTS_AVG_JOURNEY_AMOUNT=2
    volumes:
      - ./flights_avg_by_journey/config.ini:/config.ini
      - ./utils:/utils
      - ./middleware:/middleware
  flights_avg_by_journey_2:
    container_name: flights_avg_by_journey_2
    build:
      context: ./flights_avg_by_journey
      dockerfile: Dockerfile
    image: flights_avg_by_journey:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FLIGHTS_AVG_JOURNEY_ID=2
      - FLIGHTS_AVG_JOURNEY_AMOUNT=2
    volumes:
      - ./flights_avg_by_journey/config.ini:/config.ini
      - ./utils:/utils
      - ./middleware:/middleware
  manager_1:
    container_name: manager_1
    build:
      context: ./manager
      dockerfile: Dockerfile
    image: manager:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
      - MANAGER_ID=1
      - MANAGER_AMOUNT=3
      - LAYER={'flights_filter_':2,'flights_max_':2,'flights_avg_':2,'flights_mayor_avg_':2,'flights_avg_by_journey_':2,'flights_filter_distance_':2,'manager_':3}
    volumes:
      - ./utils:/utils
      - /var/run/docker.sock:/var/run/docker.sock

  manager_2:
    container_name: manager_2
    build:
      context: ./manager
      dockerfile: Dockerfile
    image: manager:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
      - MANAGER_ID=2
      - MANAGER_AMOUNT=3
      - LAYER={'flights_filter_':2,'flights_max_':2,'flights_avg_':2,'flights_mayor_avg_':2,'flights_avg_by_journey_':2,'flights_filter_distance_':2,'manager_':3}
    volumes:
      - ./utils:/utils
      - /var/run/docker.sock:/var/run/docker.sock

  manager_3:
    container_name: manager_3
    build:
      context: ./manager
      dockerfile: Dockerfile
    image: manager:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
      - MANAGER_ID=3
      - MANAGER_AMOUNT=3
      - LAYER={'flights_filter_':2,'flights_max_':2,'flights_avg_':2,'flights_mayor_avg_':2,'flights_avg_by_journey_':2,'flights_filter_distance_':2,'manager_':3}
    volumes:
      - ./utils:/utils
      - /var/run/docker.sock:/var/run/docker.sock

