version: '3.9'
services:
  rabbitmq:
    build:
      context: ./rabbitmq
    ports:
      - 15672:15672
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 10s
      timeout: 5s
      retries: 10

  post_handler_1:
    container_name: post_handler_1
    build:
      context: ./post_handler
      dockerfile: Dockerfile
    image: post_handler:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FLIGHTS_FILTER_PLUS_AMOUNT=2
      - AIRPORTS_HANDLER_AMOUNT=2
      - FLIGHTS_FILTER_AVG_AMOUNT=2
      - POST_HANDLER_ID=1
    volumes:
      - ./post_handler/config.ini:/config.ini
      - ./utils:/utils
      - ./middleware:/middleware
    ports:
      - 12351:12351
  post_handler_2:
    container_name: post_handler_2
    build:
      context: ./post_handler
      dockerfile: Dockerfile
    image: post_handler:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FLIGHTS_FILTER_PLUS_AMOUNT=2
      - AIRPORTS_HANDLER_AMOUNT=2
      - FLIGHTS_FILTER_AVG_AMOUNT=2
      - POST_HANDLER_ID=2
    volumes:
      - ./post_handler/config.ini:/config.ini
      - ./utils:/utils
      - ./middleware:/middleware
    ports:
      - 12352:12352
