version: '3.9'
services:
  rabbitmq:
    build:
      context: ./rabbitmq
    ports:
      - 15672:15672
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 10s
      timeout: 5s
      retries: 10

  post_handler:
    container_name: post_handler
    build:
      context: ./post_handler
      dockerfile: Dockerfile
    image: post_handler:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./post_handler/config.ini:/config.ini
    ports:
      - 12345:12345

  flights_filter_plus_3_1:
    container_name: flights_filter_1
    build:
      context: ./flights_filter
      dockerfile: Dockerfile
    image: flights_filter:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FLIGHTS_FILTER_PLUS_AMOUNT=4 
      - FLIGHTS_MAX_AMOUNT=4
    volumes:
      - ./flights_filter/config.ini:/config.ini

  flights_filter_plus_3_2:
    container_name: flights_filter_2
    build:
      context: ./flights_filter
      dockerfile: Dockerfile
    image: flights_filter:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FLIGHTS_FILTER_PLUS_AMOUNT=4 
      - FLIGHTS_MAX_AMOUNT=4
    volumes:
      - ./flights_filter/config.ini:/config.ini

  flights_filter_plus_3_3:
    container_name: flights_filter_3
    build:
      context: ./flights_filter
      dockerfile: Dockerfile
    image: flights_filter:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FLIGHTS_FILTER_PLUS_AMOUNT=4 
      - FLIGHTS_MAX_AMOUNT=4
    volumes:
      - ./flights_filter/config.ini:/config.ini

  flights_filter_plus_3_4:
    container_name: flights_filter_4
    build:
      context: ./flights_filter
      dockerfile: Dockerfile
    image: flights_filter:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FLIGHTS_FILTER_PLUS_AMOUNT=4 
      - FLIGHTS_MAX_AMOUNT=4
    volumes:
      - ./flights_filter/config.ini:/config.ini

  flights_filter_max_1:
    container_name: flights_max_1
    build:
      context: ./flights_max
      dockerfile: Dockerfile
    image: flights_max:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FLIGHTS_MAX_ID=1
      - FLIGHTS_MAX_AMOUNT=4
    volumes:
      - ./flights_max/config.ini:/config.ini

  flights_filter_max_2:
    container_name: flights_max_2
    build:
      context: ./flights_max
      dockerfile: Dockerfile
    image: flights_max:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FLIGHTS_MAX_ID=2
      - FLIGHTS_MAX_AMOUNT=4
    volumes:
      - ./flights_max/config.ini:/config.ini

  flights_filter_max_3:
    container_name: flights_max_3
    build:
      context: ./flights_max
      dockerfile: Dockerfile
    image: flights_max:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FLIGHTS_MAX_ID=3
      - FLIGHTS_MAX_AMOUNT=4
    volumes:
      - ./flights_max/config.ini:/config.ini

  flights_filter_max_4:
    container_name: flights_max_4
    build:
      context: ./flights_max
      dockerfile: Dockerfile
    image: flights_max:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FLIGHTS_MAX_ID=4
      - FLIGHTS_MAX_AMOUNT=4
    volumes:
      - ./flights_max/config.ini:/config.ini

  file_writer:
    container_name: file_writer
    build:
      context: ./file_writer
      dockerfile: Dockerfile
    image: file_writer:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./file_writer/config.ini:/config.ini
      - ./file_writer/:/out_files/

  flights_filter_avg_1:
    container_name: flights_avg_1
    build:
      context: ./flights_avg
      dockerfile: Dockerfile
    image: flights_avg:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FLIGHTS_FILTER_AVG_AMOUNT=2
    volumes:
      - ./flights_avg/config.ini:/config.ini

  flights_filter_avg_2:
    container_name: flights_avg_2
    build:
      context: ./flights_avg
      dockerfile: Dockerfile
    image: flights_avg:latest
    entrypoint: python3 ./main.py
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - FLIGHTS_FILTER_AVG_AMOUNT=2
    volumes:
      - ./flights_avg/config.ini:/config.ini

